baseURL: http://jlrd.github.io/
languageCode: en-us
title: Pragmatic SysAdmin
theme: terminal
paginate: 5

params:
  AuthorName: Joel Reed
  GitHubUser: jlrd
  contentTypeName: posts
  themeColor: green
  showMenuItems: 2
  showLanguageSelector: false
  fullWidthTheme: false
  centerTheme: false
  autoCover: true
  showLastUpdated: false

languages:
  en:
    languageName: English
    title: Pragmatic SysAdmin
    keywords: ""
    menuMore: Show more
    readMore: Read more
    readOtherPosts: Read other posts

    params:
      logo:
        logoText: Pragmatic SysAdmin
        logoHomeLink: /

    menu:
      main:
        - identifier: about
          name: About
          url: /about
        - identifier: showcase
          name: Showcase
          url: /showcase
